version: "3.8"

services:
  backend:
    build:
      context: .
      target: ${MODE:-dev}
      args:
        MODE: ${MODE:-dev}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      # FastAPI 환경변수
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
    volumes:
      # 개발모드에서만 볼륨 마운트
      - .:/app
      - /app/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start-period: 30s
      retries: 3
    networks:
      - ecg-network

networks:
  ecg-network:
    name: ecg-network
    driver: bridge
